### ISSUE TITLE
Set Container Login Credentials

### ISSUE THREAD

**Issue by jgockley62** [BioDepot/GUIdock-VNC#2]
Hi, 

I'm using docker compose to pull this image and port froward it to an IP. I'm trying to password protect that address with a user login and password but setting an environment variable doesn't work. What would you suggest. Here is my Docker-Compose.yaml file:
```
version: "3.3"

services:

  cyto:
    image: biodepot/novnc-cynetworkbma:latest
    volumes:
       - /home/jgockley/igraph_Network_Expansion:/home/jgockley/igraph_Network_Expansion
    ports:
      - "6080:6080"
    environment:
      - USER=user
      - PASSWORD=pass
```
